default: &default
  <<: *default
  account_id: ${env:AWS_ACCOUNT_ID}
  service: sample
  debug: serverless-sample:error
  api_version: v1

dev:
  <<: *default
  debug: serverless-sample:*
test:
  <<: *default
prod:
  <<: *default
